<a href="https://colab.research.google.com/github/HelloMorrisMoss/Ignition/blob/master/data_science_tools/Linear_regression_test_methods_for_R2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Test Linear Regression Methods

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
# dataset = pd.read_csv('ENTER_THE_NAME_OF_YOUR_DATASET_HERE.csv')
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [34]:
# a function to use for adjusted R^2
rows, feature_count = X.shape

def adj_r2(r2, p_feature_count, n_rows):
    '''Get the adjusted R^2 value.

    Args:
        p_feature_count (int): the number of independent variables.
        n_rows (int): the number of observations.

    Returns:
        float: the adjusted R^2 value.

    ar2 = adj_r2(0.91, 10, 100)
    print(ar2)
    >>> 0.89988764
    '''
    return 1-(1-r2)*(n_rows-1)/(n_rows-p_feature_count-1)

9568 4


## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Multiple Linear Regression

## Training the Multiple Linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


## Evaluating the Model Performance

In [0]:
from sklearn.metrics import r2_score
multiple_linear_r2 = r2_score(y_test, y_pred)

# Random Forest Regression

## Training the Random Forest Regression model on the whole dataset

In [14]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

## Predicting the Test set results

In [15]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


## Evaluating the Model Performance

In [0]:
from sklearn.metrics import r2_score
random_forest_r2 = r2_score(y_test, y_pred)

# Decision Tree Regression

## Training the Decision Tree Regression model on the Training set

In [17]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

## Predicting the Test set results

In [18]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]


## Evaluating the Model Performance

In [0]:
from sklearn.metrics import r2_score
decision_tree_r2 = r2_score(y_test, y_pred)

# Polynomial Regression

## Training the Polynomial Regression model on the Training set

In [20]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [21]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


## Evaluating the Model Performance

In [0]:
from sklearn.metrics import r2_score
polynomial_r2 = r2_score(y_test, y_pred)

# Support Vector Regression (SVR)

## Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train.reshape(-1, 1))

## Training the SVR model on the Training set

In [24]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

## Predicting the Test set results

In [25]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


## Evaluating the Model Performance

In [0]:
from sklearn.metrics import r2_score
svr_r2 = r2_score(y_test, y_pred)

# R2 Results

In [55]:
# dictionary of regressions and their R^2 values
r2_dict = {
    'Multiple linear Regression': multiple_linear_r2,
    'Random Forest Regression': random_forest_r2,
    'Decision Tree Regression': decision_tree_r2,
    'Polynomial Regression': polynomial_r2,
    'Support Vector Regression (SVR)': svr_r2
}

# default values
best = 0.0
best_name = 'What did you do?!'

# print out a table of results
print("{: <40} {: <20} {: <20}".format('Regression', 'R^2', 'Adjusted R^2'))
print('-'*80)
for key, val in r2_dict.items():
    if val > best:
        best = val
        best_name = key
    print("{: <40} {: <20} {: <20}".format(key, val, adj_r2(val, feature_count, rows)))

# print the best result
print('-'*80)
print(best_name, 'gave the best result, R^2:', best)

Regression                               R^2                  Adjusted R^2        
--------------------------------------------------------------------------------
Multiple linear Regression               0.9325315554761302   0.9325033348572768  
Random Forest Regression                 0.9615980699813017   0.961582007268756   
Decision Tree Regression                 0.9226091050550043   0.9225767340856662  
Polynomial Regression                    0.9458192606428147   0.9457965979891048  
Support Vector Regression (SVR)          0.9480784049986258   0.9480566872970672  
--------------------------------------------------------------------------------
Random Forest Regression gave the best result, R^2: 0.9615980699813017
